# Generated by Django 4.2.11 on 2024-03-14 07:07

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_book_user_address_user_birthdate_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='codeISBN',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to='data/book/coverImage'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='borrowance',
            name='deposit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='copy',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='copy',
            name='status',
            field=models.IntegerField(choices=[(0, 'hidden'), (1, 'available'), (2, 'borrowed'), (3, 'unavailable')], default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[home.models.Review.validateRating]),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='data/user/avatar/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNum',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
