# Generated by Django 4.2.11 on 2024-03-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_book_codeisbn_alter_book_coverimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'accepted'), (2, 'rejected')], default=0),
        ),
    ]
