# Generated by Django 4.2.11 on 2024-03-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_book_coverimage_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to='data/book/coverImage'),
        ),
    ]
