# Generated by Django 4.2.11 on 2024-03-20 02:40

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_book_coverimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.getBookImageURL),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdfFile',
            field=models.FileField(blank=True, null=True, upload_to=home.models.getBookImageURL),
        ),
        migrations.AlterField(
            model_name='copy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='copy',
            name='note',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.getUserImageURL),
        ),
    ]
