# Generated by Django 4.2.11 on 2024-03-20 03:00

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_book_coverimage_alter_book_pdffile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdfFile',
            field=models.FileField(blank=True, null=True, upload_to=home.models.getBookPDFURL),
        ),
    ]
