# Generated by Django 4.2.11 on 2024-03-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_book_pdffile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_address',
            field=models.EmailField(default='anphu@gmail.com', max_length=254),
        ),
    ]
