# Generated by Django 4.2.11 on 2024-03-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_user_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.EmailField(error_messages='This field is compulsory and must follow email format', help_text='Required', max_length=254),
        ),
    ]
