# Generated by Django 5.0.3 on 2024-04-02 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_alter_copy_id_alter_review_bookid"),
        ("home", "0015_book_ownerid_alter_review_bookid"),
    ]

    operations = []
