# Generated by Django 4.2.11 on 2024-04-02 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_merge_20240402_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ownerID',
        ),
    ]
