# Generated by Django 4.2.11 on 2024-04-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_book_ownerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages='This field is compulsory and must follow email format', help_text='Required', max_length=254, unique=True),
        ),
    ]
