# Generated by Django 4.2.11 on 2024-04-04 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_address',
        ),
    ]
