# Generated by Django 4.2.11 on 2024-04-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_book_entercate_alter_book_litecate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.IntegerField(choices=[(0, 'article'), (1, 'book'), (2, 'magazine'), (3, 'video/audio'), (4, 'comic'), (5, 'other')], default=0, null=True),
        ),
    ]
