# Generated by Django 4.2.11 on 2024-04-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_book_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'accepted'), (2, 'rejected')], default=0, null=True),
        ),
    ]
