# Generated by Django 5.0.3 on 2024-06-04 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0027_user_availableworkinghours_user_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="copy",
            old_name="note",
            new_name="copyID",
        ),
    ]
