# Generated by Django 4.2.11 on 2024-06-11 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_rename_note_copy_copyid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copy',
            old_name='copyID',
            new_name='note',
        ),
    ]
