# Generated by Django 5.0.3 on 2024-06-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0029_alter_borrowance_status"),
        ("home", "0029_rename_copyid_copy_note"),
    ]

    operations = []
