# Generated by Django 5.0.3 on 2024-06-15 08:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0030_merge_20240611_2059"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowance",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "request"),
                    (1, "double-check"),
                    (2, "borrowing"),
                    (3, "returned"),
                    (4, "overdue"),
                    (5, "lost"),
                ],
                default=0,
            ),
        ),
        migrations.CreateModel(
            name="BookApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "applying"), (1, "approved"), (2, "denied")],
                        default=0,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "bookID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.book"
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
