# Generated by Django 4.2.11 on 2024-03-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
