# Generated by Django 5.0.3 on 2024-03-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moderator', '0002_delete_myuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='UNTITLED', max_length=200)),
                ('author', models.CharField(default='UNKNOWN', max_length=200)),
                ('language', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
