# Generated by Django 5.0.3 on 2024-03-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='codeISBN',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to='data/book/coverImage'),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='enterCate',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='liteCate',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='naturCate',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='otherCate',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='poliCate',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='romanCate',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='socieCate',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')], default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='techCate',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.IntegerField(choices=[(0, 'Article'), (1, 'Book'), (2, 'Magazine'), (3, 'Video/Audio'), (4, 'Comic'), (5, 'Other')], default=1),
        ),
    ]
