# Generated by Django 4.2.11 on 2024-03-19 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0004_book_codeisbn_book_coverimage_book_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
